from uuid import UUID
from pydantic import BaseModel
from typing import Optional
from datetime import datetime

class ResourceBase(BaseModel):
    title: str
    description: Optional[str] = None
    type: str
    class_range: str
    subject: str
    pages: Optional[int] = 0
    rating: Optional[float] = 0.0
    downloads: Optional[int] = 0
    topics: Optional[list[str]] = []

class ResourceCreate(ResourceBase):
    pass
    # file_url is not in the request body, it will be generated by the upload endpoint

class ResourceInDB(ResourceBase):
    id: UUID
    file_url: str
    created_at: datetime
    
    class Config:
        from_attributes = True

class Resource(ResourceInDB):
    pass
